### ISSUE TITLE
Make tests in sorting algorithms consistent

### ISSUE THREAD

**Issue by alexfertel** [alexfertel/rust-algorithms#37]
Following the discussion in https://github.com/alexfertel/rust-algorithms/pull/35 it would be good to make tests consistent across sorting algorithm implementations such that they share a basic suite (calling the `sorting_tests!` macro) and then any other test that might be meaningful to that particular algorithm.

**Comment by lunchboxav** [comment]
hi, is this issue still being worked on? would love to try tackling it. thank you.

**Comment by alexfertel** [comment]
@lunchboxav All yours!

**Comment by aliencdh** [comment]
hey, is this issue still open by any chance?

**Comment by alexfertel** [comment]
> hey, is this issue still open by any chance?

I'm not sure if @lunchboxav is still working on it. But you can give it a try also!

**Comment by tim-jacobi** [comment]
Hi @alexfertel. How did you imagine this should be implemented? I'm new to Rust :)

**Comment by alexfertel** [comment]
Hey @tim-jacobi so the only thing left to do here is making `shell_sort` have the same signature as other sorting functions.

Initial efforts to use the same trait for every sorting function can be seen on PRs like [this](https://github.com/alexfertel/rust-algorithms/pull/55/files).

The idea is that all the sorting functions have very similar if not the same signature so that we can just call `sorting_tests!` to test them.

**Comment by CodingTil** [comment]
Hey.

Sooo, the simple solution would be to just make the parameter type of [`shell_sort`](https://github.com/alexfertel/rust-algorithms/blob/main/src/sorting/shell_sort.rs#L3) a `arr: &mut [T]` (etc.), right?

And the other, less, but still simple solution would be to "wrap" the following sorting functions (because they are not already) in  a `MutableSorter` (?):
 - `bucket_sort`
 - `cocktail_shaker_sort`
 - `counting_sort` (also doesn't use `sorting_tests!`)
 - `cycle_sort` (also doesn't use `sorting_tests!`)
 - `exchange_sort` (also doesn't use `sorting_tests!`)
 - `gnome_sort` (also doesn't use `sorting_tests!`)
 - `heap_sort`
 - `insertion_sort`
 - `merge_sort`
 - `odd_even_sort` (also doesn't use `sorting_tests!`)
 - `pancake_sort` (also doesn't use `sorting_tests!`)
 - `quick_sort` (also doesn't use `sorting_tests!`)
 - `radix_sort` (also doesn't use `sorting_tests!`)
 - `selection_sort`
 - `shell_sort` (also doesn't use `sorting_tests!`)
 - `stooge_sort`(also doesn't use `sorting_tests!`)
 - `tim_sort` (also doesn't use `sorting_tests!`)

Also, couldn't we just use `MutableSorter` everywhere? Or, even better, just use a `Sorter` Trait everywhere, and then provide two methods: `sort` and `sort_inplace` (where `sort` just calls `sort_inplace` in the fashion of [default implementations](https://doc.rust-lang.org/book/ch10-02-traits.html#default-implementations) on an copy of the input and returns the modified copy?).

This can probably turn into an discussion itself.

I could definitely assist in making all the sorting functions and their tests uniform, if no one else has dibs on this issue :smile:

**Comment by alexfertel** [comment]
I'm sorry for the late response @CodingTil, not sure how I missed this notification 😖 

> Or, even better, just use a Sorter Trait everywhere, and then provide two methods: sort and sort_inplace (where sort just calls sort_inplace in the fashion of [default implementations](https://doc.rust-lang.org/book/ch10-02-traits.html#default-implementations) on an copy of the input and returns the modified copy?).

Yes, I think this one would be the best approach. Only having a `Sorter` trait reduces overhead, and we want people to focus on the algorithms rather than the abstractions.

Thank you for the proposals and the thorough review! If you'd like to do this yourself, that would be awesome 🚀

**Comment by patilniraj8** [comment]
I would like to work on this too can u assign this to me
Email: nirajpatil849@gmail.com

**Comment by CodingTil** [comment]
I am currently working on it! - https://github.com/CodingTil/rust-algorithms
